### ISSUE TITLE
설정, 카피버튼 추가

### ISSUE THREAD

**Issue by goyomi** [datagenko/datagen#3]

**Comment by haron-lee** [comment]
settings 안에 있는 wrap 토글 버튼 함수가 미리 만들어져있는데 button 기준으로 되어있어서 디자인을 어떻게 해야할지 의논 해봐야할 것 같습니다!

**Comment by goyomi** [comment]
> settings 안에 있는 wrap 토글 버튼 함수가 미리 만들어져있는데 button 기준으로 되어있어서 디자인을 어떻게 해야할지 의논 해봐야할 것 같습니다!

아마 함수팀에서 예상으로 하고 미리 만들어 놓으신거같은데 ~ 함수부분도 같이 바꾸어주면 동작도 잘하고 크게 문제는 없을 것 같습니다! 일단 순서가 디자인>마크업>함수기 때문에 고치시고 말씀해주시면 함수팀으로 내용 공유하겠습니다!

**Comment by goyomi** [comment]
font-size 부분이 빠졌다는 연락을 받아서 코드 추가해두었습니다
